
set -g default-terminal "screen-256color"

# Prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# VI mode
set-window-option -g mode-keys vi

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' # some default sensible configs
set -g @plugin 'dracula/tmux' # theme
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux session after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically save sessions every 15 minutes

# Theme settings
set -g @dracula-plugins " "
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g status-position top

# Save session after restart
set -g @continuum-restore 'on'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
